apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: backend-secret
  data:
  - secretKey: username
    remoteRef:
      key: my-db-secret
      property: username
  - secretKey: password
    remoteRef:
      key: my-db-secret
      property: password
